# Generated by Django 4.1.5 on 2023-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('G_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=13)),
                ('Gender', models.CharField(max_length=25)),
                ('Date_of_Birth', models.DateTimeField()),
                ('Addresse', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gardian',
            },
        ),
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('S_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Admin_id', models.CharField(max_length=255)),
                ('T_id', models.CharField(max_length=255)),
                ('Subject_id', models.CharField(max_length=255)),
                ('Desability_id', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Education_level', models.CharField(max_length=255)),
                ('Date_of_Birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Item2',
            fields=[
                ('T_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Admin_id', models.CharField(max_length=255)),
                ('S_id', models.CharField(max_length=255)),
                ('Subject_id', models.CharField(max_length=255)),
                ('Schedule_id', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Experience', models.CharField(max_length=255)),
                ('Date_of_Birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Item3',
            fields=[
                ('G_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=13)),
                ('Gender', models.CharField(max_length=25)),
                ('Date_of_Birth', models.DateTimeField()),
                ('Addresse', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Item4',
            fields=[
                ('G_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=13)),
                ('Gender', models.CharField(max_length=25)),
                ('Date_of_Birth', models.DateTimeField()),
                ('Addresse', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Item5',
            fields=[
                ('G_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=13)),
                ('Gender', models.CharField(max_length=25)),
                ('Date_of_Birth', models.DateTimeField()),
                ('Addresse', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
    ]
