# Generated by Django 4.1.7 on 2023-02-24 15:57

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('Admin_id', models.CharField(default=api.models.random_prA, max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('T_id', models.CharField(max_length=255)),
                ('S_id', models.CharField(default=api.models.random_prS, max_length=100)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('Desability_id', models.CharField(default=api.models.Disability.random_prD, max_length=255, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=255)),
                ('Disabilitys', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Disability',
            },
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('Schedle_id', models.CharField(default=api.models.random_prSc, max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('T_id', models.CharField(max_length=100)),
                ('S_id', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.DateField()),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('Subject_id', models.CharField(default=api.models.random_prSu, max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('T_id', models.CharField(default=api.models.random_prT, max_length=100)),
                ('S_id', models.CharField(default=api.models.random_prS, max_length=100)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('T_id', models.CharField(default=api.models.random_prT, max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=225, unique=True)),
                ('Admin_id', models.CharField(default=api.models.random_prA, max_length=100, null=True)),
                ('S_id', models.CharField(default=api.models.random_prS, max_length=100, null=True)),
                ('Subject_id', models.CharField(default=api.models.random_prSu, max_length=100, null=True)),
                ('Schedule_id', models.CharField(default=api.models.random_prSc, max_length=100, null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Experience', models.CharField(max_length=255, null=True)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Addrese', models.CharField(max_length=255, null=True, unique=True)),
                ('Expert_IN', models.CharField(max_length=255)),
                ('Review', models.IntegerField(blank=True, null=True)),
                ('certificate', models.ImageField(upload_to=api.models.teacher.FileName)),
                ('Goverment_id', models.ImageField(upload_to=api.models.teacher.FileName)),
                ('Photo', models.ImageField(upload_to=api.models.teacher.FileName)),
                ('Signature', models.ImageField(upload_to=api.models.teacher.FileName)),
                ('Payment', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('S_id', models.CharField(default=api.models.random_prS, max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Admin_id', models.CharField(default=api.models.random_prA, max_length=100)),
                ('T_id', models.CharField(default=api.models.random_prT, max_length=100, null=True)),
                ('Subject_id', models.CharField(default=api.models.random_prT, max_length=100, null=True)),
                ('Gender', models.CharField(max_length=255)),
                ('Education_level', models.CharField(max_length=255, null=True)),
                ('Date_of_Birth', models.DateField()),
                ('Desability_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disability')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('Accept_id', models.CharField(default=api.models.random_prAc, max_length=25, primary_key=True, serialize=False)),
                ('Message', models.CharField(default='I want help', max_length=255)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'db_table': 'Join_Request',
            },
        ),
        migrations.CreateModel(
            name='gardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_Name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=13)),
                ('Relationship', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=25)),
                ('Addresse', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=255, unique=True)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'Gardian',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fingerprint', models.ImageField(upload_to=api.models.Attendence.FileName)),
                ('Date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'db_table': 'Attendence',
            },
        ),
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default=api.models.random_room_name, max_length=255)),
                ('is_accepted', models.BooleanField(default=0)),
                ('Accept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request')),
            ],
            options={
                'db_table': 'Room_name',
            },
        ),
    ]
